### ISSUE TITLE
v14.0?

### ISSUE THREAD

**Issue by angelleye** [matatirosolutions/filemakerapi#2]
Glad to see you've done this.  It's perfect!

I see you've tagged everything to match the FM versions.  I don't see 14.0, though..??  Looks like that's in the master branch, but not tagged..??  Is it ready to use?

**Comment by steveWinter** [comment]
Somewhat late to replying - it was indeed in master, it was ready to use, and it, along with 15 is now tagged. I've also added a note to the readme that 15.x is the last tag sine FMI haven't made any changes to the API since.
